// Smart Account client layer.
//
// Wraps smart-account-kit (OpenZeppelin Stellar accounts + WebAuthn passkeys).
// This is the single place the apps and setup scripts construct the kit, so
// network/infra config stays in one spot.
//
// Contract calls go through `signAndSubmitTx`: a dicekey contract binding
// (generated by `scripts/generate-bindings.sh`) produces an
// `AssembledTransaction`, which the kit signs (passkey), re-simulates and
// submits. smart-account-kit@0.2.10 has no `executeAndSubmit`; `signAndSubmit`
// is the supported path.

import {
  SmartAccountKit,
  IndexedDBStorage,
  type StorageAdapter,
  type AssembledTransaction,
  type TransactionResult,
} from "smart-account-kit";
import { getConfig } from "./config.js";

/**
 * Options forwarded to the kit's `signAndSubmit`.
 *
 * `resolveContextRuleIds` is the U2 multi-context path: staff-app's
 * visit-stamps.issue auth tree makes 3 admin.require_auth calls, so the OZ
 * __check_auth needs context_rule_ids index-aligned to the 3 auth_contexts
 * (issue@visit-stamps, mint@beans-token, on_stamp_issued@reward-policy).
 * customer-app never passes this — its single-context calls are unaffected.
 *
 * `entry` is typed `unknown` to avoid dragging @stellar/stellar-sdk's `xdr`
 * (and its node typings) into strict browser tsconfigs; the kit accepts the
 * callback structurally and our callers ignore the entry (return a fixed
 * rule-id vector). Cast inside the callback if entry inspection is ever needed.
 */
export interface SignSubmitOptions {
  credentialId?: string;
  expiration?: number;
  resolveContextRuleIds?: (
    entry: unknown,
    index: number,
  ) => number[] | Promise<number[]>;
}

export interface CreateKitOptions {
  /** Override credential storage (default: IndexedDBStorage; node scripts pass MemoryStorage). */
  storage?: StorageAdapter;
  /** Override the contract this kit connects to (e.g. the HQ Smart Account for staff). */
  rpIdOverride?: string;
}

/**
 * Build a fresh SmartAccountKit from the active NetworkConfig.
 *
 * Throws early with an actionable message if the Testnet infra env vars are
 * missing — the usual cause is forgetting to copy `.env.testnet` into the app.
 */
export function createKit(opts: CreateKitOptions = {}): SmartAccountKit {
  const cfg = getConfig();
  const sa = cfg.smartAccount;

  const missing: string[] = [];
  if (!sa.accountWasmHash) missing.push("VITE_ACCOUNT_WASM_HASH");
  if (!sa.webauthnVerifierAddress) missing.push("VITE_WEBAUTHN_VERIFIER_ADDRESS");
  if (missing.length > 0) {
    throw new Error(
      `Smart Account config missing: ${missing.join(", ")}. ` +
        `Run scripts/deploy-testnet.sh and copy .env.testnet into the app.`,
    );
  }

  return new SmartAccountKit({
    rpcUrl: cfg.rpcUrl,
    networkPassphrase: cfg.networkPassphrase,
    accountWasmHash: sa.accountWasmHash,
    webauthnVerifierAddress: sa.webauthnVerifierAddress,
    rpId: opts.rpIdOverride ?? sa.rpId,
    rpName: sa.rpName,
    // Rule ids are pinned via env (VITE_HQ_STAFF_CONTEXT_RULE_ID); the indexer
    // is only needed for reverse lookup / rule enumeration, which we don't use.
    indexerUrl: false,
    storage: opts.storage ?? new IndexedDBStorage(),
    // Undefined when VITE_WORKER_URL is unset (localnet): kit.relayer stays
    // null and submissions go through rpc. When set, kit auto-routes
    // invokeHostFunction submissions through the Worker relayer.
    relayerUrl: cfg.relayerUrl,
  });
}

let kitInstance: SmartAccountKit | null = null;

/** Process-wide kit singleton for the browser apps. */
export function getKit(): SmartAccountKit {
  if (!kitInstance) kitInstance = createKit();
  return kitInstance;
}

export function resetKit() {
  kitInstance = null;
}

/**
 * Sign (passkey) + re-simulate + submit an AssembledTransaction produced by a
 * generated dicekey contract binding client.
 *
 * @example
 *   await signAndSubmitTx(visitStamps.issue({ admin: hqSA, to: customerSA, venue }))
 */
export async function signAndSubmitTx<T>(
  tx: AssembledTransaction<T>,
  opts?: SignSubmitOptions,
): Promise<TransactionResult> {
  return getKit().signAndSubmit(tx, opts);
}

// Re-export the kit surface the apps & setup scripts need, so everything goes
// through a single resolved copy of smart-account-kit.
export {
  SmartAccountKit,
  IndexedDBStorage,
  MemoryStorage,
  LocalStorageAdapter,
  createDefaultContext,
  createCallContractContext,
  createWebAuthnSigner,
  createDelegatedSigner,
  createThresholdParams,
  createSpendingLimitParams,
  WalletNotConnectedError,
  SimulationError,
  SubmissionError,
  WebAuthnError,
} from "smart-account-kit";
export type {
  StorageAdapter,
  AssembledTransaction,
  TransactionResult,
  CreateWalletResult,
  ConnectWalletResult,
  ContextRule,
  ContextRuleType,
  ContractSigner,
} from "smart-account-kit";
