// Aggregates the per-contract TypeScript bindings generated by
// `scripts/generate-bindings.sh` into typed clients for the 5 dicekey
// contracts.
//
// Each generated binding does `export * from "@stellar/stellar-sdk"`, so we
// import ONLY the `Client` class from each (re-exporting all would collide).
// Client methods return `AssembledTransaction`, which is handed to
// `signAndSubmitTx` (smart-account-kit) for passkey signing + submission.

// Import the generated bindings from their COMPILED output (./<c>/dist), not
// raw src. The codegen (`stellar contract bindings typescript`) emits unused
// imports that trip a consumer's noUnusedLocals; building each binding under
// its own tsconfig (unused-checks off) and consuming the emitted .d.ts means
// strict consumers (customer-app: noUnusedLocals/Params) only see the .d.ts,
// which skipLibCheck excludes from those diagnostics. Run
// `pnpm --filter @dicekey/contracts build` (scripts/generate-bindings.sh and
// the app builds do this) to (re)produce the dist outputs.
import { Client as VisitStampsClient } from "./visit-stamps/dist/index.js";
import { Client as BeansTokenClient } from "./beans-token/dist/index.js";
import { Client as BenefitsClient } from "./benefits/dist/index.js";
import { Client as BadgesClient } from "./badges/dist/index.js";
import { Client as RewardPolicyClient } from "./reward-policy/dist/index.js";

export {
  VisitStampsClient,
  BeansTokenClient,
  BenefitsClient,
  BadgesClient,
  RewardPolicyClient,
};

export interface DicekeyClientsOptions {
  rpcUrl: string;
  networkPassphrase: string;
  contracts: {
    visitStamps: string;
    beansToken: string;
    benefits: string;
    badges: string;
    rewardPolicy: string;
  };
  /**
   * Source account the AssembledTransactions are built for. Use the connected
   * Smart Account C-address; smart-account-kit re-simulates & signs auth on
   * top. Optional for read-only (simulate) usage.
   */
  publicKey?: string;
}

export interface DicekeyClients {
  visitStamps: VisitStampsClient;
  beansToken: BeansTokenClient;
  benefits: BenefitsClient;
  badges: BadgesClient;
  rewardPolicy: RewardPolicyClient;
}

/** Construct all 5 typed contract clients from network config + contract ids. */
export function makeDicekeyClients(o: DicekeyClientsOptions): DicekeyClients {
  const base = {
    rpcUrl: o.rpcUrl,
    networkPassphrase: o.networkPassphrase,
    publicKey: o.publicKey,
  };
  return {
    visitStamps: new VisitStampsClient({ ...base, contractId: o.contracts.visitStamps }),
    beansToken: new BeansTokenClient({ ...base, contractId: o.contracts.beansToken }),
    benefits: new BenefitsClient({ ...base, contractId: o.contracts.benefits }),
    badges: new BadgesClient({ ...base, contractId: o.contracts.badges }),
    rewardPolicy: new RewardPolicyClient({ ...base, contractId: o.contracts.rewardPolicy }),
  };
}
