#!/usr/bin/env bash
set -euo pipefail

# Build customer-app, staff-app, and sa-harness into a single Cloudflare
# Pages dist tree at dist-pages/. staff-app lives at /staff/ and the HQ
# bootstrap UI (tools/sa-harness) at /setup/, all under the same host.
# Same-host is mandatory: WebAuthn rpId scoping (pages.dev sits in the
# Public Suffix List → no subdomain sharing) means the HQ root passkey
# minted at /setup/ MUST be created with the same rpId apps/staff-app
# uses at /staff/, which can only happen if the two paths share an origin.
#
# Layout produced:
#   dist-pages/
#     index.html             customer-app SPA shell
#     assets/                customer-app's hashed JS/CSS
#     manifest.json
#     _headers               customer-app's headers (used as the merged root)
#     _redirects             /staff/* -> /staff/index.html,
#                            /setup/* -> /setup/index.html,
#                            /*       -> /index.html
#     staff/
#       index.html           staff-app SPA shell (Vite injects base=/staff/)
#       assets/              staff-app's hashed JS/CSS
#       manifest.json
#     setup/
#       index.html           sa-harness HQ bootstrap UI (base=/setup/)
#       assets/              sa-harness's hashed JS/CSS
#
# Run AFTER apps/*/.env.production + tools/sa-harness/.env.production exist,
# or you'll deploy with placeholder / blank values. deploy-testnet.sh writes
# tools/sa-harness/.env.production automatically.
#
# Prereqs:
#   - .env.testnet exists + apps/{customer,staff}-app/.env.production filled
#   - tools/sa-harness/.env.production exists (deploy-testnet.sh mirrors it)
#   - pnpm install + pnpm --filter @dicekey/contracts build done

cd "$(dirname "$0")/.."

OUT_DIR="dist-pages"

# 🟡 Sanity: every .env.production must exist. We don't validate every key —
#    Vite would happily inline empty values and the app would just fail at
#    runtime. The user copies values from .env.testnet (or the harness
#    Step-4 output) into apps/*/.env.production once per network reset;
#    tools/sa-harness/.env.production is generated by deploy-testnet.sh.
for f in apps/customer-app/.env.production apps/staff-app/.env.production tools/sa-harness/.env.production; do
  if [ ! -f "$f" ]; then
    echo "ERROR: $f missing." >&2
    echo "       apps/*/.env.production: copy from .env.production.example and fill from .env.testnet." >&2
    echo "       tools/sa-harness/.env.production: regenerated by scripts/deploy-testnet.sh." >&2
    exit 1
  fi
done

echo "=== Cleaning $OUT_DIR ==="
rm -rf "$OUT_DIR"

echo "=== Building customer-app (base=/) ==="
pnpm --filter customer-app build

echo "=== Building staff-app (base=/staff/) ==="
# Vite --base overrides whatever's in vite.config.ts at build time. tsc runs
# first (the filter's `build` script chains tsc -b && vite build); we call
# them separately so --base flows to vite only.
pnpm --filter staff-app exec tsc -b
pnpm --filter staff-app exec vite build --base=/staff/

echo "=== Building sa-harness (base=/setup/) ==="
# sa-harness has no tsconfig (Vite handles TS transpile alone). Default mode
# = production, so Vite reads tools/sa-harness/.env.production — the one
# deploy-testnet.sh wrote with VITE_RP_ID=dicekey-coffee-stamps.pages.dev so
# the HQ root passkey created here can be consumed by /staff/ on the same
# host origin.
pnpm --filter sa-harness exec vite build --base=/setup/

echo "=== Merging into $OUT_DIR ==="
# customer-app dist becomes the root. Its _redirects already carries the
# /staff/* and /setup/* fallback rules (see public/_redirects).
cp -r apps/customer-app/dist/. "$OUT_DIR/"

# staff-app dist drops into /staff/. CF Pages only honors _headers /
# _redirects at the merged root, so the per-app copies inside /staff/
# would be ignored anyway — remove them to keep the deployed tree clean.
mkdir -p "$OUT_DIR/staff"
cp -r apps/staff-app/dist/. "$OUT_DIR/staff/"
rm -f "$OUT_DIR/staff/_headers" "$OUT_DIR/staff/_redirects"

# sa-harness dist drops into /setup/. Same root-only _headers/_redirects
# rule as staff-app above. The setup UI is single-page (no router), but
# /setup/* still falls back to /setup/index.html so a hard refresh on the
# URL never 404s on CF Pages.
mkdir -p "$OUT_DIR/setup"
cp -r tools/sa-harness/dist/. "$OUT_DIR/setup/"
rm -f "$OUT_DIR/setup/_headers" "$OUT_DIR/setup/_redirects"

echo ""
echo "=== Output ($OUT_DIR) ==="
( cd "$OUT_DIR" && find . -maxdepth 2 -type f | sort )

echo ""
echo "Done."
echo "Deploy: just deploy-pages    (= wrangler pages deploy $OUT_DIR --project-name=dicekey-coffee-stamps)"
